gulpfile.js
package.json

Implement coverage as we do in other repositories. It now opens `index.html` in the browser after running.
Uses [`nyc`](https://github.com/istanbuljs/nyc).

Fix coverage

---

index.js
lib/getGoogleGroupLinks.js
lib/getUniqueMatch.js
specs/lib/getGoogleGroupLinksSpec.js
specs/lib/getUniqueMatchSpec.js

Remove `lib/RegexTools.js` in favor of files which export one function:
- `lib/getUniqueMatch.js`
- `lib/getGoogleGroupLinks.js`

Replace RegexTools with one file per function

---

.gitignore
.npmignore
.travis.yml
gulpfile.js
package.json

Fixes #19 
Add wrapper around `npm shrinkwrap` in order to package `cesium-concierge` for deployment.
Tested by running the command, unzipping the generated file, and running `npm test` and `npm start` to verify things were working.
/cc @mramato look OK?

Add `create-zip` gulp task

---

lib/commentOnClosedIssue.js
specs/lib/getUniqueMatchSpec.js

Huge oversight: the google group regex will not find google group links
- "embedded" in markdown
- followed by `\n` or `\r`
This fixes these cases and adds a unit test to confirm.

Fix google link regex to parse markdown link

---

Dockerfile

This is just a minor security best practice to not run as root in the Docker container in the off chance that a Docker escape/elevatione exploit it uncovered.

Don't run server as Docker root.

---

Dockerfile
bin/stalePullRequest.js
crontab
supervisord.conf

@omh1280 while I couldn't figure out the cron issue for non-root users (we'll just run root for now), I did find a bunch of issues with how you were setting up cron and made the following changes:
1. Rather than trying to set things up manually, use crontab to import the existing cron file as documented in the man page.
2. supervisord was running cron incorrectly, needed `-l` not `-L`.
3. Redirect all supervisord task output to stdout and stderr
4. Specify the supervisord configuration file directly rather than relying on putting it in `/etc`.
5. Remove unnecessary `root` specification in crontab.
Can you please test and merge.
Also, it looks like you have the task set up to run every minute, obviously that's far too often.  I assume once a day is probably enough.  Please make this change …

User crontab to correctly set up cron.

---

bin/stalePullRequest.js
specs/bin/stalePullRequestSpec.js
specs/data/responses/pullRequestComments.json

Since the `updated_at` value of PRs seem to be updated by nothing, we'll use another way of measuring PR staleness.
This pull request checks the last comment's `created_at` date as a metric for the PR's staleness. Ideally, it would be the latest of comments' AND commits' `created_at`, but I don't have time to do that today.

Check staleness of PR by last comment `created_at`

---

README.md
lib/RepositorySettings.js
lib/commentOnOpenedPullRequest.js
lib/postToGitHub.js
lib/templates/pullRequestOpened.hbs
specs/lib/commentOnOpenedPullRequestSpec.js
specs/lib/postToGitHubSpec.js

The bot will always post a single message when a new PR is open and indicate whether the user has a CLA or not (so we can interpret the lack of a post as meaning something went wrong instead of assuming false
positive).
If claUrl is not configured, then we just thank them for the PR.
I configured this repository to use the Cesium CLA list, so we'll know right away if this works.

Adds support for CLA checking.

---

lib/commentOnClosedIssue.js
specs/lib/getUniqueMatchSpec.js

Fixes #61
Only matches threads or message links to the `cesium-dev` forum.

Adjust forum regex to only match forum posts

---

.concierge/templates/signature.hbs
.idea/jsLibraryMappings.xml
lib/RepositorySettings.js
lib/Settings.js
lib/commentOnClosedIssue.js
lib/commentOnOpenedPullRequest.js
lib/loadRepoConfig.js
lib/templates/signature.hbs
specs/lib/RepositorySettingsSpec.js
specs/lib/commentOnClosedIssueSpec.js
specs/lib/commentOnOpenedPullRequestSpec.js
specs/lib/loadRepoConfigSpec.js

Fixes #73
Allow repository settings and templates to be loaded from files stores in the github repo. These settings will override the environment variables and default config files.
Configuration file naming and structure that it will look for:
```
.concierge/
templates/
signature.hbs
...
config.json
```

Load repository settings from the github repo

---

lib/RepositorySettings.js
lib/loadRepoConfig.js
specs/lib/commentOnClosedIssueSpec.js
specs/lib/loadRepoConfigSpec.js

Renamed `signature`->`signatureTemplate` so it can be loaded without special condition.
Also decode file contents from github so loaded templates are properly displayed.
@mramato

Template fixes

---

lib/RepositorySettings.js
lib/commentOnOpenedPullRequest.js
lib/templates/pullRequestOpened.hbs
specs/lib/commentOnOpenedPullRequestSpec.js

The concierge should still post, and the error will be logged to stdout in the event the CLA request fails or does not parse.

Catch and log errors parsing CLA.json

---

README.md
lib/RepositorySettings.js
lib/commentOnOpenedPullRequest.js
lib/templates/pullRequestOpened.hbs
specs/lib/commentOnOpenedPullRequestSpec.js

Resolves https://github.com/AnalyticalGraphicsInc/cesium-concierge/issues/84
For this to work in the Cesium repository, we have to add to `contributorsUrl` to the Concierge settings in that repository. That url should be:
```
https://api.github.com/repos/AnalyticalGraphicsInc/cesium/contents/CONTRIBUTORS.md
```
This works by just checking the username of the account that opened the PR and parses `CONTRIBUTORS.md` to check all the usernames in there. A future PR can also abstract this method as a way to tell if this is a first time contributor to display other helpful messages, (as opposed to having to say "If this is your first PR do this" every time).
For tests, I added two separate tests to check the cases of when it should post a reminder vs when it should not. Let me know if those …

Remind first time contributors to add name to CONTRIBUTORS.md

---

lib/loadRepoConfig.js
specs/lib/loadRepoConfigSpec.js

I'm not sure if this ever worked, but the content returned from `requestPromise.get` returns a base64 encoded string, so trying to parse it as a JSON was failing when a repo had configuration settings in `.concierge/config.json`.

Fixed parsing of repo settings

---

Dockerfile

Concierge is currently broken because it's running with `/bin/sh` which doesn't like our environment variables (which are not valid because they have characters like `-` and `/` in them). The solution is to use `/bin/bash` and that requires at least `npm 5` so it's a good reason to update.
I tested this locally and all tests run. I couldn't actually confirm this solves the problem locally because I can't set environment variables like that on the command line (because they're invalid). I'm not sure what magic AWS does behind the scenes to force these environment variables in. 
I know this works because I ssh'ed into the running instance and ran a test script that showed it is correctly printing out the environment variables when running with `/bin/bash`. @mramato this should be a quick …

Update node and set shell to bash

---

package.json

I didn't realize the bumper had an `npm` start script. Since it's part of the application now this is no longer needed.
@ggetz

Bumper start script no longer needed

---

.ebextensions/timezone.config
Dockerfile

Currently concierge runs on an AWS server by default configured for UTC time. This makes the script bumper run at 5 pm our time instead of midnight. Which isn't a big deal, but our Slackbot will also be running on the same server and it'd be nice to post things in the morning in a timely manner.
This will set the correct timezone inside the Docker container. Since we're using a stripped down version of Linux (alpine) we need to install `tzdata` for timezones to work.
@ggetz

Add timezone setting

---

lib/stalePullRequest.js
specs/lib/stalePullRequestSpec.js

This implements https://github.com/AnalyticalGraphicsInc/cesium-concierge/issues/60. The bumper will now fetch the commits on a PR, check the date of the latest one, and if both that date and the date of the last comment are more than X number of days, it will bump.
This also fixes an edge case where a PR has no comments, concierge would crash (this is unlikely to ever happen since there will almost always be at least the concierge's initial comment) but it was easy enough to fix. If there are no comments it will use the PR's created_at date.
I added a spec to test that it will not bump if there is a recent commit.

Make stale PR bumper check for recent commits

---

lib/SlackBot.js
specs/lib/SlackBotSpec.js

This was totally my bad, but the Slack bot's unit tests weren't actually checking if it calls the Slack API so it missed a typo/syntax error.

Make sure Slackbot actually calls Slack API

---

lib/templates/weeklyStats.hbs

This makes Slackbot's weekly stats message slightly more concise. Since this databox link is always the last link, it gets expanded into a preview. I think it's not very useful since it's only for CesiumJS (it requires payment to aggregate multiple sources I think, plus we don't have as fine grained control over it as Slackbot's stats message). 
This will help because I think the next step is making Concierge watch more repo's, so it can be reporting how many PRs we've merged across all repo's.

Remove Databox dashboard from Slackbot message

---

lib/commentOnOpenedPullRequest.js

Concierge failed to look up a CLA that we know was in a corporate Schedule A (https://github.com/AnalyticalGraphicsInc/cesium/pull/8076#issuecomment-521684344). This was because the block of text returned from the Google Sheets API has extra control characters at the end that need to be trimmed before doing a string comparison. 
Tested this by running concierge locally with the corporate CLA spreadsheet to confirm it now correctly detects it. 
There was also a typo in that it was setting `foundIndividualCLA` regardless of whether it was the corporate or individual, but that doesn't change the returned result either way.

Trim words in corporate CLA check

---

lib/SlackBot.js
lib/commentOnClosedIssue.js
package.json
specs/lib/SlackBotSpec.js
specs/lib/commentOnClosedIssueSpec.js

This fixes https://github.com/AnalyticalGraphicsInc/cesium-concierge/issues/135 and adds a test to ensure that it works.
Slackbot will currently report that a PR was merged last week even if it was merged a long time ago, but someone commented on it last week. The other problem is getting a list of pull requests doesn't differentiate `merged` from `closed`. In order to check if a `PR` is merged or not we need to make another API request. This complicated the code a bit so I refactored it should be a lot simpler now. 
While working on this I also noticed the way we were authenticating with GitHub using the OctokitJS libary was deprecated so I updated that as well. 
Coverage is still high at ~95% and all new code is 100% covered. 
TODO:

Only report last week's PRs in weekly stats

---

.slackbot.yml
.travis.yml
lib/SlackBot.js
lib/templates/releaseReminder.hbs
lib/templates/releaseReminderEarly.hbs
lib/templates/releaseReminderLate.hbs
lib/templates/weeklyStats.hbs
specs/data/slackbot.yml
specs/lib/SlackBotSpec.js

Fixes https://github.com/CesiumGS/cesium-concierge/issues/142 to make the slack bot send individuals on the team reminders when the release is happening.
* Changed structured of the `.slackbot.yml` to be an array instead of a dict, so that people can be listed more than once
* Removed the weekly stats message which we're not really using anymore
* Updated unit tests
* Updated node to fix Travis, but can't use node 12 because of this issue https://stackoverflow.com/questions/55921442/how-to-fix-referenceerror-primordials-is-not-defined-in-node ?
I've tested this locally with a mock YAML and confirmed the Slack bot will message me. Here is what the 3 messages look like (I've updated the links to be AGI -> CesiumGS):
To do

Fix release notifications

---

lib/SlackBot.js
lib/templates/releaseReminder.hbs
lib/templates/releaseReminderEarly.hbs
lib/templates/releaseReminderLate.hbs
specs/lib/SlackBotSpec.js

This PR makes the slack bot post release reminders to the general `#dev` channel instead of directly to individuals that way everyone is aware when the release is happening and who's leading it. 
This required using the `userId` instead of the name so the user gets notified (this is what `link_names: true` does, see https://api.slack.com/methods/chat.postMessage#arg_link_names)
I also needed to use three curly brackets in the handlebars template to allow the special characters `<` in the message since the syntax is `<@userId>`.

Make concierge post release reminders to #dev Slack channel

---

README.md
lib/RepositorySettings.js
lib/commentOnOpenedPullRequest.js
specs/lib/commentOnOpenedPullRequestSpec.js

Adds an option to check the GitHub contributors list for first-time contributors. This is useful if CONTRIBUTORS.md is not maintained in the repo, and GitHub Contributors API can be used.
Here is a simple gulp task that can be used from CLI
```
var Promise = require('bluebird');
var requestPromise = require('request-promise');
gulp.task('contributors', function () {
var repositoryContributorsUrl = 'https://api.github.com/repos/AnalyticalGraphicsInc/cesium/contributors';
var contributorsPromises = [];
for (var i = 1; i < 6; i++) { // GitHub maintains only 500 named contributors
contributorsPromises[i - 1] = requestPromise.get({
url: repositoryContributorsUrl,
qs: {
per_page: 100,
page: i
},
headers: {
'User-Agent': 'cesium-concierge'
},
json: true
});
}
return …
```

Add API for GitHub Contributors during ask about contributors check
